### ISSUE TITLE
INSTALL ASKS FOR LATEST MAXTHON WHEN IT IS ALREADY INSTALLED

### ISSUE THREAD

**Issue by raisinc** [abdllhbyrktr/mx-pdfjs-viewer#1]
I tried installing this extension but it states that I must have the latest Maxthon installed to use extensions!
I am actually running version 5.2.3.4 (there is no later version)
Is there a fix for this or is there another way to read PDF files internally within Maxthon now?

**Comment by abdllhbyrktr** [comment]
I just installed the latest beta version and did not see a problem. Could you try the beta version of Maxthon. Here is the [link](http://forum.maxthon.com/index.php?/release-notes5/nbspnbspnbspnbspnbspnbspnbspnbspv-5241100-r166/).

**Comment by raisinc** [comment]
The link you supplied does not work. I do not wish to run under a “Beta” version
anyway (could be buggy) 

 

But I have found the solution! J

 

I have switched the mode of Maxthon over to “Ultra” mode and PDF’s now

open up within Maxthon, so there is no longer any need for your extension.

 

As a test I tried installing your extension again while the browser is in “Ultra” mode

and now the install works! It seems that a user must put the Maxthon browser into

“Ultra” mode instead of “Retro” mode before installing any extensions.

 

So now under “Settings” I have changed Maxthon to always run under “Ultra” mode.

That should fix things permanently.

 

Does your extension do anything else apart from allowing Maxthon to display PDFs

internally? If so, then it seems the latest release of Maxthon removes the need for the
extension (in the Maxthon browser at least).

 

Thanks for your time and I apologise for any inconvenience.

 

Kindest regards

 

Chris

**Comment by 02030pllolipop** [comment]
staled

**Comment by raisinc** [comment]
That link to he latest version does not work anymore, not surprisingly.
I gather the word "Staled" just means that this ticket is now "closed"(?)
I had actually already forgotten about the problem. Nowadays I am tending to stop using Maxthon (never thought I would say that) and am using the new Edge (which is getting better and better as time marches on).
