### ISSUE TITLE
Blinking with a night mode pllugin

### ISSUE THREAD

**Issue by 02030pllolipop** [abdllhbyrktr/mx-pdfjs-viewer#2]
Draging causse blinking with this on:
Maxthon - Extensions Center
http://extension.maxthon.com/detail/index.php?view_id=3060

**Comment by abdllhbyrktr** [comment]
I don't exactly understand the problem. But I upgraded PDF.js library to the latest version. You can try it in releases section.

**Comment by 02030pllolipop** [comment]
@abdllhbyrktr sorry for the ambiguity as i thought the author has gone :P 
You would need to activate that plugin on the top to have the blinking.
Both clicking and dragging will cause blinking.
Gif here: 
![123](https://user-images.githubusercontent.com/7941949/47484503-69554c00-d86e-11e8-9653-9ef86095b232.gif)

**Comment by abdllhbyrktr** [comment]
Thank you @kliop00023 for your clear explanation. I cannot reproduce this issue in my browser, everything seems normal. Also my Maxthon's version is 5.2.5.1000. Maybe this problem is related to your theme. Do you have any theme in your browser?

**Comment by 02030pllolipop** [comment]
@abdllhbyrktr still exist here:
![123](https://user-images.githubusercontent.com/7941949/47793277-e42fd280-dd58-11e8-8f0e-9144ae7798e9.gif)

**Comment by 02030pllolipop** [comment]
Still exists. may b/c of old PC+users theme
